### ISSUE TITLE
As a user I want to be rewarded for my continuous playing

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_client#108]
- [x] sopra-fs24-group-23/sopra24_client#109
- [x] sopra-fs24-group-23/sopra24_client#111
- [x] sopra-fs24-group-23/sopra24_server#172
- [x] sopra-fs24-group-23/sopra24_server#173
- [x] sopra-fs24-group-23/sopra24_server#174
- [x] sopra-fs24-group-23/sopra24_client#123
- [x] sopra-fs24-group-23/sopra24_client#124
- [x] sopra-fs24-group-23/sopra24_client#129
- [x] sopra-fs24-group-23/sopra24_client#128
